import base64
import io
from PIL import Image
import numpy as np
import tensorflow as tf
from flask import Flask, request, jsonify
from flask_cors import CORS
import joblib
import pandas as pd

app = Flask(__name__)
CORS(app)

app.config["MAX_CONTENT_LENGTH"] = 10 * 1024 * 1024

model = tf.keras.models.load_model('breast_cancer_model.h5')
scaler = joblib.load('scaler.save')

def preprocess_features(features):
    features_scaled = scaler.transform([features])
    return features_scaled

@app.route('/api/predict', methods=['POST'])
def predict():
    if 'file' not in request.files:
        return jsonify({"error": "No file part"}), 400

    file = request.files['file']
    if file.filename == '':
        return jsonify({"error": "No selected file"}), 400

    try:
        df = pd.read_csv(file)
        features = df.iloc[0].drop('diagnosis', errors='ignore').values.astype(float)
    except Exception as e:
        return jsonify({"error": f"Invalid CSV file: {e}"}), 400

    try:
        features_scaled = preprocess_features(features)
        pred_prob = model.predict(features_scaled)[0][0]
        pred_class = "Cancer" if pred_prob > 0.5 else "No Cancer"
        confidence_score = float(pred_prob) * 100

        diagnosis_summary = (
            "**AI Diagnosis Report**\n\n"
            f"**Prediction:** {pred_class}\n"
            f"**Confidence Score:** {confidence_score:.2f}%\n\n"
            "This report is generated by an AI system and is for informational purposes only."
        )

        return jsonify({
            "prediction": pred_class,
            "confidence": confidence_score,
            "summary": diagnosis_summary
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0')
