from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.responses import JSONResponse, FileResponse
from fastapi.middleware.cors import CORSMiddleware
import uvicorn
import numpy as np
import tensorflow as tf
from PIL import Image
import io
import os
import pandas as pd
import joblib
from typing import Optional
from starlette.background import BackgroundTask

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load models and scaler
csv_model = tf.keras.models.load_model('breast_cancer_model.h5')
scaler = joblib.load('scaler.save')
image_model = tf.keras.models.load_model('breast_cancer_image_model.h5')

def preprocess_features(features):
    features_scaled = scaler.transform([features])
    return features_scaled

def preprocess_image(image_bytes):
    img = Image.open(io.BytesIO(image_bytes)).convert('RGB')
    img = img.resize((224, 224))
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    return img_array

@app.post("/predict/csv")
async def predict_csv(file: UploadFile = File(...)):
    if not file.filename.endswith('.csv'):
        raise HTTPException(status_code=400, detail="File must be a CSV")
    contents = await file.read()
    try:
        df = pd.read_csv(io.BytesIO(contents))
        features = df.iloc[0].drop(['diagnosis', 'id', 'Unnamed: 32'], axis=1, errors='ignore').values.astype(float)
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Invalid CSV file: {e}")

    features_scaled = preprocess_features(features)
    pred_prob = csv_model.predict(features_scaled)[0][0]
    pred_class = "Cancer" if pred_prob > 0.5 else "No Cancer"
    confidence_score = float(pred_prob) * 100

    diagnosis_summary = (
        "**AI Diagnosis Report**\n\n"
        f"**Prediction:** {pred_class}\n"
        f"**Confidence Score:** {confidence_score:.2f}%\n\n"
        "This report is generated by an AI system and is for informational purposes only."
    )

    return JSONResponse({
        "prediction": pred_class,
        "confidence": confidence_score,
        "gradCamUrl": "/images/grad-cam-heatmap.png",
        "summary": diagnosis_summary
    })

@app.post("/predict/image")
async def predict_image(file: UploadFile = File(...)):
    if not file.filename.lower().endswith(('.png', '.jpg', '.jpeg', '.dcm')):
        raise HTTPException(status_code=400, detail="File must be an image (PNG, JPG, JPEG, DICOM)")
    contents = await file.read()
    try:
        img_array = preprocess_image(contents)
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Invalid image file: {e}")

    pred_prob = image_model.predict(img_array)[0][0]
    pred_class = "Cancer" if pred_prob > 0.5 else "No Cancer"
    confidence_score = float(pred_prob) * 100

    # Placeholder for Grad-CAM heatmap URL (to be implemented)
    grad_cam_url = "/images/grad-cam-heatmap.png"

    diagnosis_summary = (
        "**AI Diagnosis Report**\n\n"
        f"**Prediction:** {pred_class}\n"
        f"**Confidence Score:** {confidence_score:.2f}%\n\n"
        "This report is generated by an AI system and is for informational purposes only."
    )

    return JSONResponse({
        "prediction": pred_class,
        "confidence": confidence_score,
        "gradCamUrl": grad_cam_url,
        "summary": diagnosis_summary
    })

@app.get("/report/{scan_id}")
async def get_report(scan_id: str):
    # Placeholder: Implement report generation and storage
    report_path = f"reports/{scan_id}.pdf"
    if not os.path.exists(report_path):
        raise HTTPException(status_code=404, detail="Report not found")
    return FileResponse(report_path, media_type='application/pdf', filename=f"report_{scan_id}.pdf")

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
